# Generated by Django 5.0.4 on 2024-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_fotografia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'NEBULOSA'), ('GALÁXIA', 'GALÁXIA'), ('PLANETA', 'PLANETA'), ('ESTRELA', 'ESTRELA')], default='', max_length=255),
        ),
    ]
