# Generated by Django 5.0.4 on 2024-05-01 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da Fotografia'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
