# Generated by Django 5.0.4 on 2024-05-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_fotografia_alter_fotografia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'NEBULOSA'), ('GALÁXIA', 'GALÁXIA'), ('PLANETA', 'PLANETA'), ('ESTRELA', 'ESTRELA')], default='', max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/%Y/%m/%d/', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='legenda',
            field=models.CharField(max_length=255, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
