# Generated by Django 5.0.4 on 2024-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
